### ISSUE TITLE
Usage instructions

### ISSUE THREAD

**Issue by joarwilk** [iamchenxin/flow-graphql#1]
I have no idea how to use this, haven't used a custom schema printer before. This repo could really use some basic instructions.

**Comment by iamchenxin** [comment]
@joarwilk Did you refer to `printSchema`? I temporary add a option `hierarchy`(and default order is `alphabet` which is graphql's origin printSchema) for it.

So If call `printSchema` like `printSchema(schema, 'hierarchy')`:
It will print schema as a leaf->root order.( The leaf Type is at the top, the root Type is at the bottom) You can check the behaviour in [ unit test](https://github.com/iamchenxin/graphql-js/blob/8efc6f6a290798dd91d76570debe19deb3783df3/src/utilities/__tests__/schemaPrinter-test.js#L1593).

This function is used to print readable schema for me, because i prefer to read a leaf->root order, not a alphabet order.
